source 'https://rubygems.org'

gem 'pry'
gem 'mechanize'
gem 'main', '~> 4.7.6'
gem 'fukung',  '~> 1.1.0'
gem 'yajl-ruby', '~> 1.0.0'
gem 'nokogiri', '~> 1.5.0'
gem 'google-search', '~> 1.0.2'
gem 'unidecode', '~> 1.0.0'
gem 'systemu', '~> 2.3.0'
gem 'flowdock'
